
blank_issues_enabled: false
contact_links:
  - name: Suport
    url: https://github.com/cnecrea/vreaulanova/discussions
    about: Dacă problema ta nu se potrivește cu un template, poți cere ajutor în secțiunea de discuții.
